### PR TITLE
Bug 536067 - Update license to EPL 2.0

### PR DESCRIPTION
**Pull request by lukasj**
Signed-off-by: Lukas Jungmann <lukas.jungmann@oracle.com>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=536067

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=536067

**Comment by lukasj** [comment]
@bshannon my bad, I overlooked EDL part :-( should be back. Thanks for catching this!

**Comment by lukasj** [comment]
@bshannon :
re about.html - that reference points to the license under which JPA 2.2 binary is included, that license has not been updated yet, see https://github.com/lukasj/eclipselink-oracleddlparser/blob/a272c2aa78605d637e8c59714be3110c57c4261d/oracleddlparser/src/main/resources/about.html#L167

re license.html - fixed by 96f87f2

**Pull request merged**
